const express = require("express");
const healthRoutes = require("./health.routes");
const authRoutes = require("./auth.routes");
const propertyRoutes = require("./property.routes");
const propertyOwnerRoutes = require("./propertyOwner.routes");
const propertyBankRoutes = require("./propertyBank.routes");
const ownerRoutes = require("./owner.routes");
const bankAccountRoutes = require("./bankAccount.routes");
const paymentMethodRoutes = require("./paymentMethod.routes");
const clientRoutes = require("./client.routes");
const bookingRoutes = require("./booking.routes");
const paymentRoutes = require("./payment.routes");
const expenseRoutes = require("./expense.routes");
const commissionRoutes = require("./commission.routes");
const transferRoutes = require("./transfer.routes");
const propertyTransferRoutes = require("./propertyTransfer.routes");
const propertyHistoryRoutes = require("./propertyHistory.routes");
const propertyDocumentRoutes = require("./propertyDocument.routes");
const propertyMediaRoutes = require("./propertyMedia.routes");
const inventoryRoutes = require("./inventory.routes");
const employeeRoutes = require("./employee.routes");
const vendorRoutes = require("./vendor.routes");
const recurringRoutes = require("./recurring.routes");
const budgetRoutes = require("./budget.routes");
const pettyCashRoutes = require("./pettyCash.routes");
const auditLogRoutes = require("./auditLog.routes");
const maintenanceRoutes = require("./maintenance.routes");
const favoriteRoutes = require("./favorite.routes");
const calendarRoutes = require("./calendar.routes");
const recycleBinRoutes = require("./recycleBin.routes");
const searchRoutes = require("./search.routes");
const backupRoutes = require("./backup.routes");
const uploadsRoutes = require("./uploads.routes");
const dashboardRoutes = require("./dashboard.routes");
const reportRoutes = require("./report.routes");
const notificationRoutes = require("./notification.routes");
const healthController = require("../controllers/health.controller");

const router = express.Router();

router.get("/", healthController.getRoot);
router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/uploads", uploadsRoutes);

// Nested property relationship routes before generic /properties/:id
router.use("/properties/:propertyId/owners", propertyOwnerRoutes);
router.use("/properties/:propertyId/bank-accounts", propertyBankRoutes);
router.use("/properties/:propertyId/transfers", propertyTransferRoutes);
router.use("/properties/:propertyId/history", propertyHistoryRoutes);
router.use("/properties/:propertyId/documents", propertyDocumentRoutes);
router.use("/properties/:propertyId/media", propertyMediaRoutes);
router.use("/properties/:propertyId/visits", require("./propertyVisit.routes"));
router.use("/properties", propertyRoutes);
router.use("/owners", ownerRoutes);
router.use("/bank-accounts", bankAccountRoutes);
router.use("/payment-methods", paymentMethodRoutes);
router.use("/clients", clientRoutes);
router.use("/bookings", bookingRoutes);
router.use("/payments", paymentRoutes);
router.use("/expenses", expenseRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/employees", employeeRoutes);
router.use("/vendors", vendorRoutes);
router.use("/recurring-expenses", recurringRoutes);
router.use("/budgets", budgetRoutes);
router.use("/petty-cash", pettyCashRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/maintenance", maintenanceRoutes);
router.use("/favorites", favoriteRoutes);
router.use("/calendar", calendarRoutes);
router.use("/recycle-bin", recycleBinRoutes);
router.use("/search", searchRoutes);
router.use("/backups", backupRoutes);
router.use("/commissions", commissionRoutes);
router.use("/transfers", transferRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/reports", reportRoutes);
router.use("/notifications", notificationRoutes);

module.exports = router;
